# Generated by Django 5.0.7 on 2024-07-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBotMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('message_type', models.CharField(choices=[('input', 'Input'), ('response', 'Response'), ('system', 'System')], max_length=100)),
                ('is_response', models.BooleanField(default=False)),
                ('is_system_message', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='chat_messag_timesta_93c8bf_idx'), models.Index(fields=['is_active'], name='chat_messag_is_acti_52ba05_idx')],
            },
        ),
    ]
