# Generated by Django 5.0.7 on 2024-07-15 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'conversations',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='chat.chatbotmessages')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='chat.conversation')),
            ],
            options={
                'db_table': 'contents',
                'ordering': ['created_at'],
            },
        ),
    ]
