# Generated by Django 5.0.7 on 2024-07-15 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Content',
            new_name='Contents',
        ),
        migrations.RenameModel(
            old_name='Conversation',
            new_name='Conversations',
        ),
    ]
