# Generated by Django 5.0.7 on 2024-07-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_contents_content_message_conversationcontents'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversations',
            name='message_type',
            field=models.CharField(choices=[('input', 'Input'), ('response', 'Response'), ('system', 'System')], default='input', max_length=100),
        ),
    ]
