# Generated by Django 5.0.7 on 2024-07-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_conversations_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationcontents',
            name='link',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='conversationcontents',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
